### ISSUE TITLE
iOS devices reset TOS on every page reload

### ISSUE THREAD

**Issue by rene-giretzlehner** [saleemkce/timeonsite#1]
I tested TOS on an iPhone X: https://saleemkce.github.io/timeonsite/
As long as I stay on the same page (without reload) the counter goes up. When I reload the page, both counters are reset to 0.

Additionally the realtime callbacks are not firing on iOS when leaving the page or just navigating between multiple pages on the same domain.

**Comment by saleemkce** [comment]
@rene-giretzlehner sorry for delayed reply. I think there might be two issues.
1, check if Javascript is enabled in the mobile browser [cookie enabled](https://www.verizonwireless.com/support/knowledge-base-206711/)
2, Some older versions of **Opera/Safari** don't support browser unload event which may be reason for realtime callback not firing. In that case, we can't track timeonsite since lack of support in browser API. You might consider delayed approach with following setting,
```
request: {
  url: 'http://localhost:4500/tos', //your endpoint URL to which data would be sent via POST method in API call
},
```
while initializing timeonsite tracker.

**Comment by saleemkce** [comment]
@rene-giretzlehner any progress in your timeonsitetracker integration?

**Comment by niitprachi** [comment]
Hi @saleemkce ,
I tried to verify this issue on iPhone 7 plus and it does replicate. 'Time On Site (in seconds)'
 behaves just like 'Time On Page (in seconds)'. When page is reloaded it starts from 0


iOS - 12.4.1
Safari

**Comment by saleemkce** [comment]
@niitprachi , there is a cookie reset issue in iphone itself. It belongs to IOS devices, I have raised a ticket in IOS mobile issues. It'll work only if issue is resolved from their side.  I verify most other devices and browsers are free from this issue.

**Comment by saleemkce** [comment]
For those interested to fix it in IOS browser, check this https://bugs.chromium.org/p/chromium/issues/detail?id=844847 issue of Apple WKCookieStore IOS browser-specific

**Comment by saleemkce** [comment]
@rene-giretzlehner @niitprachi   Thanks for your early reporting. 

It's been recently found that the report that Chromium made on **cookie was not working in short intervals like 1 second in IOS mobile devices** is not compatible. And developers from Chromium site linked above  https://bugs.chromium.org/p/chromium/issues/detail?id=844847  actually **misguided us with this feedback**.  The actual behavior is that even IOS devices support short time cookies properly but the problem was with **window Unload** events that don't work at all in any IOS mobile devices.

   We recently found this accidentally and therefore we started writing a **major separate software patch** to support IOS mobile devices. This is not actually a problem with [timeonsitetracker.js](https://github.com/saleemkce/timeonsite) itself but unexpectedly a lack of support on major window events in IOS mobile browsers & devices.

  Our software patch has been in the stages of completion. Our initial tests show it works on all major versions of **IPhone, Ipad and IOS safari browser**s along with **a wide range of Linux browsers**.  This software patch is concentrated for IOS mobile devices only because all major desktop browsers like **Chrome, Firefox, Edge, Safari, Opera** are already working normally with highest accuracy level ever available for timeonpage and timeonsite tracking in web space. These devices contribute more than 95% of all internet traffic; so we get to measure unique time on site data entirely.

  Stay tuned for the news on the release of major **timeonsitetracker.js** version that's going to impact the way timeonsite analytics is made on user data.

**Comment by saleemkce** [comment]
A major patch has been written overcoming the **IOS webkit window event drawbacks** and deployed in demo page https://saleemkce.github.io/timeonsite , a breakthrough in measuring time-on-site parameter for web & mobile browsers. This should now work fine in all IOS devices like **IPhone**, **Ipad** etc.  Official [release on repo page](https://github.com/saleemkce/timeonsite) is soon underway.

#timeonpage 
#timeonpage
#timeonsite-tracking-JS

**Comment by saleemkce** [comment]
Tag [version V1.1.0 released](https://github.com/saleemkce/timeonsite/releases/tag/v1.1.0) that fixes this issue in IOS devices.
