### ISSUE TITLE
Tos.startSession

### ISSUE THREAD

**Issue by JStika** [saleemkce/timeonsite#4]
I'm using php Nette framework v. 2.4 (https://doc.nette.org/en/2.4/sessions).

If I use after login: Tos.startSession("user_"+tosCustomData.userId);
and if I use after logout: Tos.endSession();
I got php error, please see img. 
Can you help me?
![debug](https://user-images.githubusercontent.com/722942/79135922-662a8480-7db0-11ea-9d1b-b8ce41d81d68.jpg)

**Comment by saleemkce** [comment]
When you click logout() in UI, immediately call **_Tos.endSession();_** Give (or delay) few milliseconds, then allow your function hit the backend server for PHP logout logic.  That should be fine.

**Comment by saleemkce** [comment]
When you call Tos.endSession(), you are clearing following cookies which are used by Tracker. The timing should be in sync between calling this function and subsequently hitting backend logout() logic. Cookies being cleared:

_TOSUserId
TOSSessionKey
TOSSessionDuration_

Put few logs and check. It should be straight forward.

**Comment by saleemkce** [comment]
@JStika have you adjusted calling start and end session functions? is it working now?

**Comment by JStika** [comment]
Hi,

I found where problem is. 
I've problem on windows 10, xammp only. I've no problem on webhosting server (Linux OS).
I checked my php.ini and Heureka! My php.ini is different.

All works properrly for now.

**Comment by saleemkce** [comment]
A general idea here for all trying to track authenticated users:

Time on site tracker is a **stream of tracking data** which means it keeps monitoring the time on page data the moment we enter a web page and ends only at the moment website is closed. It doesn't differentiate between who the user it, halt, stop or give a interval while the user switches, be it anonymous or authenticated. It continuously tracks with minimal or no UI distraction **aimed at data precision**.

Since cookie is modified at the point while we switch among anonymous or authenticated user, the general steps should be like,

```
// a few hundred milliseconds delay after the backend login logic is done can be applied only if required 
Tos.startSession('exampleUserId');
```

```
// a few hundred milliseconds delay before the backend logout logic is done can be applied only if required
Tos.endSession()
```

```
// Example code to make a trivial delay in calling login/logout logic.
Tos.endSession();
setTimeout(function() {
     App.callLogoutLogic();  // your app logout backend API call
}, 600)  // 0.6 second delay; 
```

to ensure cookie clash issues.

**Comment by saleemkce** [comment]
@JStika kindly close the issue if it solved the problem.

**Comment by JStika** [comment]
It's OK for me now.

**Comment by JStika** [comment]
But, another issue:
    if (tosSessionManager === 1) {
        Tos.startSession("user_"+tosCustomData.userId);
        Tos.extendSession({$cookieLifeTime|noescape});
	} else if (tosSessionManager === 2) {
        Tos.endSession();
	}

Variable $cookieLifeTime is cookie life time from  Nette framework (+14 days).
If I use Tos.extendSession({$cookieLifeTime|noescape}); I see in console current datetime and not datetime + 14 days.
